name: "audio_processing"
backend: "python"

input [
  {
    name: "AUDIO_INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "SPECTROGRAM_OUTPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]