name: "bert_embedding"
backend: "python"

input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "EMBEDDING"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]

instance_group [{ kind: KIND_CPU }]