name: "len_rev"
backend: "python"

input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "LENGTH"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "REVERSED"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]